
name: Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build-package
      - name: macOS Binary
        uses: actions/upload-artifact@v2
        with:
          name: quick-rename-macos
          path: build/quick-rename-macos
      - name: Window Binary
        uses: actions/upload-artifact@v2
        with:
          name: quick-rename-win
          path: build/quick-rename-win.exe
